<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
Schema::create('templates', function (Blueprint $t){$t->id();$t->string('name');$t->string('slug')->unique();$t->string('type');$t->string('thumbnail')->nullable();$t->text('description')->nullable();$t->json('config_json')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
Schema::create('events', function (Blueprint $t){$t->id();$t->foreignId('user_id')->constrained();$t->foreignId('template_id')->constrained('templates');$t->string('title');$t->string('slug')->unique();$t->string('event_type');$t->string('status')->default('draft');$t->string('main_title');$t->text('short_description')->nullable();$t->string('cover_image')->nullable();$t->string('music_url')->nullable();$t->text('intro_note')->nullable();$t->text('main_quote')->nullable();$t->text('footer_text')->nullable();$t->unsignedBigInteger('views_count')->default(0);$t->timestamp('published_at')->nullable();$t->json('custom_data_json')->nullable();$t->timestamps();});
Schema::create('event_timelines', function (Blueprint $t){$t->id();$t->foreignId('event_id')->constrained()->cascadeOnDelete();$t->string('title');$t->date('event_date')->nullable();$t->text('description')->nullable();$t->string('icon')->nullable();$t->unsignedInteger('sort_order')->default(0);$t->boolean('is_active')->default(true);$t->timestamps();});
Schema::create('trips', function (Blueprint $t){$t->id();$t->foreignId('event_id')->constrained()->cascadeOnDelete();$t->string('title');$t->string('slug');$t->string('location')->nullable();$t->string('cover_image')->nullable();$t->date('start_date')->nullable();$t->date('end_date')->nullable();$t->string('duration_text')->nullable();$t->string('weather_text')->nullable();$t->string('mood_text')->nullable();$t->text('opening_note')->nullable();$t->longText('diary_text')->nullable();$t->text('ending_quote')->nullable();$t->text('map_url')->nullable();$t->text('footer_text')->nullable();$t->unsignedInteger('sort_order')->default(0);$t->boolean('is_active')->default(true);$t->timestamps();});
Schema::create('trip_images', function (Blueprint $t){$t->id();$t->foreignId('trip_id')->constrained()->cascadeOnDelete();$t->string('image_path');$t->string('caption')->nullable();$t->unsignedInteger('sort_order')->default(0);$t->timestamps();});
Schema::create('trip_memories', function (Blueprint $t){$t->id();$t->foreignId('trip_id')->constrained()->cascadeOnDelete();$t->string('content');$t->unsignedInteger('sort_order')->default(0);$t->timestamps();});
Schema::create('trip_schedules', function (Blueprint $t){$t->id();$t->foreignId('trip_id')->constrained()->cascadeOnDelete();$t->string('time_text')->nullable();$t->string('title');$t->text('description')->nullable();$t->string('icon')->nullable();$t->unsignedInteger('sort_order')->default(0);$t->timestamps();});
Schema::create('destination_wishlists', function (Blueprint $t){$t->id();$t->foreignId('event_id')->constrained()->cascadeOnDelete();$t->string('title');$t->unsignedInteger('sort_order')->default(0);$t->timestamps();});
Schema::create('event_views', function (Blueprint $t){$t->id();$t->foreignId('event_id')->constrained()->cascadeOnDelete();$t->string('ip_address',45)->nullable();$t->text('user_agent')->nullable();$t->timestamp('viewed_at')->nullable();$t->timestamps();});
} public function down(): void {foreach(['event_views','destination_wishlists','trip_schedules','trip_memories','trip_images','trips','event_timelines','events','templates'] as $tb){Schema::dropIfExists($tb);} }};
